package com.mindblown.webdown;


import java.io.File;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author beamj
 */
public class FailedUrlDataPanel extends javax.swing.JPanel {
    
    private UrlDownData data;
    private FileAction fa;

    /**
     * Creates new form FailDataPanel
     * @param data
     * @param fa
     */
    public FailedUrlDataPanel(UrlDownData data, FileAction fa) {
        this.data = data;
        initComponents();
        this.fa = fa;
    }
    
    public void change(){
        fa.addUrlToDown(new UrlDownData(data.getParentData(), new Ref(urlField.getText()), fileField.getText() + "", tagField.getText() + "", downResultField.getText() + ""));
    }
    
    private String formatDownloadResult(){
        String res = Util.strip(data.getDownloadResult() + "");
        return res;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        urlField = new javax.swing.JTextField();
        fileField = new javax.swing.JTextField();
        tagField = new javax.swing.JTextField();
        downResultField = new javax.swing.JTextField();
        dirButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        changeButton = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(7, 0));

        urlField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        urlField.setText(data.getUrl().toString());
        urlField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                urlFieldMouseClicked(evt);
            }
        });
        add(urlField);

        fileField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fileField.setText(data.getRefFile());
        fileField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fileFieldMouseClicked(evt);
            }
        });
        add(fileField);

        tagField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tagField.setText(data.getTag());
        add(tagField);

        downResultField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        downResultField.setText(formatDownloadResult());
        add(downResultField);

        dirButton.setText("Open Dir");
        dirButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dirButtonMouseClicked(evt);
            }
        });
        add(dirButton);

        deleteButton.setText("Delete");
        deleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteButtonMouseClicked(evt);
            }
        });
        add(deleteButton);

        changeButton.setText("Change");
        changeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeButtonMouseClicked(evt);
            }
        });
        add(changeButton);
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseClicked
        FailedUrlsPanel.panel.disposeAndRemove();
    }//GEN-LAST:event_deleteButtonMouseClicked

    private void changeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeButtonMouseClicked
        change();
        FailedUrlsPanel.panel.disposeAndRemove();
    }//GEN-LAST:event_changeButtonMouseClicked

    private void fileFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fileFieldMouseClicked
        if(evt.getClickCount() != 2){
            return;
        }
        Util.open(new File(data.getRefFile()));
    }//GEN-LAST:event_fileFieldMouseClicked

    private void urlFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_urlFieldMouseClicked
        if(evt.getClickCount() != 2){
            return;
        }
        Util.open(data.getUrl().toString());
    }//GEN-LAST:event_urlFieldMouseClicked

    private void dirButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dirButtonMouseClicked
        Util.openDir(new File(data.getRefFile()));
    }//GEN-LAST:event_dirButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changeButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton dirButton;
    private javax.swing.JTextField downResultField;
    private javax.swing.JTextField fileField;
    private javax.swing.JTextField tagField;
    private javax.swing.JTextField urlField;
    // End of variables declaration//GEN-END:variables
}
