
import java.awt.event.KeyEvent;
import java.io.File;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JDialog;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author beamj
 */
public class FailedUrlsPanel extends javax.swing.JPanel {
    
    private UrlListModel model;
    public static FailedUrlsPanel panel;
    private JDialog dial;
    private UrlDownData selected;
    private FileAction fa;
    
    public FailedUrlsPanel(){
        model = new UrlListModel();
        initComponents();
        panel = this;
    }

    /**
     * Creates new form DownFailPanel
     * @param data
     * @param fa
     */
    public FailedUrlsPanel(ArrayList<UrlDownData> data, FileAction fa) {
        model = new UrlListModel(data);
        initComponents();
        panel = this;
        this.fa = fa;
    }
    
    public void thoroughEnable(boolean enable){
        jScrollPane1.setEnabled(enable);
        urlList.setEnabled(enable);
    }
    
    public void setFailedUrls(File downFailFile, FileAction fa){
        String text = Util.getText(downFailFile);
        text = Util.strip(text);
        CacheScanner scan = UrlDownData.getScan();
        ArrayList<UrlDownData> data = Cacheable.convert(scan, text, fa.getServerTree());
        this.fa = fa;
        model.setData(data);
    }
    
    public static FailedUrlsPanel genDownloadFailPan(File downFailFile, FileAction fa){
        String text = Util.getText(downFailFile);
        text = Util.strip(text);
        CacheScanner scan = UrlDownData.getScan();
        ArrayList<UrlDownData> data = Cacheable.convert(scan, text, fa.getServerTree());
        return new FailedUrlsPanel(data, fa);
    }

    public UrlListModel getModel() {//TEST APP AND FINDS THE DATILED LOGS THAT ARE USING THE WRONG REF FILE.
        return model;
    }
    
    private void openData(){
        int selectedRow = urlList.getSelectedIndex();
        if(selectedRow == -1){
            return;
        }
        UrlDownData d = (UrlDownData) model.getElementAt(selectedRow);
        selected = d;
        FailedUrlDataPanel failedUrlDataPanel = new FailedUrlDataPanel(d, fa);
        dial = Util.showNorm(failedUrlDataPanel, "Data");
        dial.setVisible(true);
    }
    
    public void addFailedUrl(UrlDownData d){
        model.add(d);
        reset();
    }
    
    private void reset(){
        urlList.revalidate();
//        MainFrame.main.repaint();
    }
    
    private void removeData(UrlDownData d){
        model.remove(d);
        reset();
    }
    
    public void disposeAndRemove(){
        dial.dispose();
        model.remove(selected);
        reset();
        Cacheable.cache(model.getData(), MainFrame.downFailFile);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        urlList = new javax.swing.JList<>();

        setLayout(new java.awt.GridLayout(1, 0));

        jScrollPane1.setBorder(null);

        urlList.setModel(model);
        urlList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                urlListMouseClicked(evt);
            }
        });
        urlList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                urlListKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(urlList);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents

    private void urlListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_urlListMouseClicked
        if(evt.getClickCount() != 2){
            return;
        }
        openData();
    }//GEN-LAST:event_urlListMouseClicked

    private void urlListKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_urlListKeyPressed
        int code = evt.getKeyCode();
        char c = evt.getKeyChar();
        if(code == KeyEvent.VK_DELETE){
            int[] selectedInds = urlList.getSelectedIndices();
            Arrays.sort(selectedInds);
            for(int i = selectedInds.length - 1; i >= 0; i--){
                UrlDownData selectedData = (UrlDownData) model.getElementAt(selectedInds[i]);
                if(selectedData != null){
                    removeData(selectedData);
                } else {
                    System.out.println("(FailedUrlsPanel::urlListKeyPressed:a) recieved null.");
                }
            }
            reset();
        } else if(code == KeyEvent.VK_ENTER){
            openData();
        } else if(code == KeyEvent.VK_C || c == 'c'){
            int[] selectedInds = urlList.getSelectedIndices();
            Arrays.sort(selectedInds);
            for(int i = selectedInds.length - 1; i >= 0; i--){
                selected = (UrlDownData)model.getElementAt(selectedInds[i]);
                if(selected != null){
                    fa.addUrlToDown(selected);
                    model.remove(selectedInds[i]);
                } else {
                    System.out.println("(FailedUrlsPanel::urlListKeyPressed:b) recieved null.");
                }
            }
            reset();
        }
    }//GEN-LAST:event_urlListKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> urlList;
    // End of variables declaration//GEN-END:variables
}
